name: Renovate config validate

on:
    pull_request:

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

            -   name: Cache node_modules
                uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
                env:
                    cache-name: cache-node_modules
                with:
                    path: node_modules
                    key: test-${{ env.cache-name }}-${{ hashFiles('package-lock.json') }}
                    restore-keys: |
                        test-${{ env.cache-name }}-
                        test-

            -   uses: jdx/mise-action@1648a7812b9aeae629881980618f079932869151 # v4.0.1

            -   run: npm install

            -   name: Validate renovate config
                run: |
                    find \
                        . \
                        -maxdepth 1 \
                        -type f \
                        -name "*.json" \
                        -not -name package.json \
                        -not -name package-lock.json \
                        -exec basename {} \; | \
                    sort | \
                    xargs npx renovate-config-validator --strict
